/**
 * Application chrome: skip link, banner header with navigation, main landmark
 * and content-info footer.
 *
 * The landmark structure here is what lets keyboard and screen-reader users
 * jump straight past the header into the page content.
 */

import { Box, Container, Flex, HStack, Link as ChakraLink, Text } from '@chakra-ui/react'
import type { ReactNode } from 'react'
import { NavLink, Link as RouterLink } from 'react-router-dom'

import ColorModeToggle from './ColorModeToggle'

const NAV_ITEMS = [{ label: 'Dashboard', to: '/' }]

/** Target of the skip link; also the accessible name anchor for `<main>`. */
export const MAIN_CONTENT_ID = 'main-content'

export interface AppShellProps {
  children: ReactNode
}

export function AppShell({ children }: AppShellProps) {
  return (
    <Flex direction="column" minH="100vh" bg="bg.canvas">
      {/* First focusable element on the page. */}
      <ChakraLink href={`#${MAIN_CONTENT_ID}`} className="skip-link">
        Skip to main content
      </ChakraLink>

      <Box
        as="header"
        borderBottomWidth="1px"
        borderColor="border.subtle"
        bg="bg.surface"
        position="sticky"
        top={0}
        zIndex="sticky"
      >
        <Container maxW="80rem" px={{ base: 4, md: 6 }}>
          <Flex align="center" justify="space-between" h={{ base: 14, md: 16 }} gap={4}>
            <HStack spacing={{ base: 3, md: 8 }} minW={0}>
              <ChakraLink
                as={RouterLink}
                to="/"
                display="flex"
                alignItems="center"
                gap={2}
                fontWeight={700}
                fontSize="md"
                color="fg.default"
                letterSpacing="-0.02em"
                _hover={{ textDecoration: 'none', color: 'accent.fg' }}
              >
                <Box
                  aria-hidden="true"
                  w={7}
                  h={7}
                  borderRadius="md"
                  bg="accent.solid"
                  color="#FFFFFF"
                  display="grid"
                  placeItems="center"
                  fontSize="sm"
                  fontWeight={800}
                >
                  ₿
                </Box>
                Crypto Viewer
              </ChakraLink>

              <Box as="nav" aria-label="Main navigation">
                <HStack as="ul" listStyleType="none" spacing={1}>
                  {NAV_ITEMS.map((item) => (
                    <Box as="li" key={item.to}>
                      <ChakraLink
                        as={NavLink}
                        to={item.to}
                        end
                        px={3}
                        py={1.5}
                        borderRadius="md"
                        fontSize="sm"
                        fontWeight={600}
                        color="fg.muted"
                        _hover={{ bg: 'bg.subtle', color: 'fg.default', textDecoration: 'none' }}
                        // NavLink adds `aria-current="page"` on the active route.
                        _activeLink={{ bg: 'accent.subtle', color: 'accent.fg' }}
                      >
                        {item.label}
                      </ChakraLink>
                    </Box>
                  ))}
                </HStack>
              </Box>
            </HStack>

            <ColorModeToggle />
          </Flex>
        </Container>
      </Box>

      <Box as="main" id={MAIN_CONTENT_ID} flex="1" tabIndex={-1} outline="none">
        <Container maxW="80rem" px={{ base: 4, md: 6 }} py={{ base: 6, md: 8 }}>
          {children}
        </Container>
      </Box>

      <Box as="footer" borderTopWidth="1px" borderColor="border.subtle" bg="bg.surface">
        <Container maxW="80rem" px={{ base: 4, md: 6 }} py={5}>
          <Text fontSize="xs" color="fg.muted">
            Prices and balances are supplied by the Coinbase Advanced Trade API. Analysis is
            generated by a language model and is not financial advice.
          </Text>
        </Container>
      </Box>
    </Flex>
  )
}

export default AppShell
